// ============================================================================
// Workbook Activity Inventory — canonical source-of-truth for all activities
// Generated: 2026-06-24
// ============================================================================

export type InteractionType =
  | "SINGLE_CHOICE"
  | "MATCHING"
  | "ORDERING"
  | "OPEN_TEXT"
  | "SELF_ASSESSMENT"
  | "FILL_BLANK"
  | "WORD_BANK"
  | "THREE_ANSWERS"
  | "PROBLEM_SOLUTION"
  | "STORY_BUILDER"
  | "AGREE_DISAGREE";

export type GradingMode = "OBJECTIVE" | "OPEN" | "SELF_ASSESSMENT";

export type StoragePolicy =
  | "FULL_RESPONSE"
  | "OBJECTIVE_RESULT_ONLY"
  | "COMPLETION_ONLY"
  | "NO_PERSISTENCE";

export type ImplementationStatus =
  | "IMPLEMENTED"
  | "REVIEW_ACTIVITY"
  | "MERGED_WITH_REASON"
  | "BLOCKED_CONTENT_REVIEW";

export interface WorkbookActivityItem {
  sourceItemKey: string;
  sourcePage: number;
  journeySlug: string;
  stageSlug: string;
  originalPrompt: string;
  normalizedPrompt: string;
  sourceOptions: string[];
  sourceCorrectAnswer: string;
  sourceModelAnswer: string;
  interactionType: InteractionType;
  gradingMode: GradingMode;
  storagePolicy: StoragePolicy;
  requiresAudio: boolean;
  implementationStatus: ImplementationStatus;
  mergedIntoSourceItemKey?: string;
  notes?: string;
}

export const workbookActivityInventory: WorkbookActivityItem[] = [
  // ============================================================================
  // JOURNEY 1: ancient-egyptian-teacher (أسرار المعلم المصري القديم)
  // Items 1–22
  // ============================================================================

  // --- Writing/Prediction ---
  {
    sourceItemKey: "j1-01",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "predict",
    originalPrompt: "اكتب ثلاثة عناوين مناسبة للخبر المسموع",
    normalizedPrompt: "Write three suitable titles for the listened news",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "1. مكانة المعلم في مصر القديمة\n2. الكاتب المصري ودوره في نشر العلم\n3. أوراق البردي وسر الكتابة",
    interactionType: "THREE_ANSWERS",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes: "Seeded as titles-generation (three_answers). Matches workbook.",
  },
  {
    sourceItemKey: "j1-02",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "predict",
    originalPrompt: "اكتب ثلاثة أسئلة يريد الطالب طرحها",
    normalizedPrompt: "Write three questions the student wants to ask",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "1. كيف تم العثور على المقبرة؟\n2. ما هي الأدوات التي دفنت معه؟\n3. كيف كان يعلم الكاتب طلابه؟",
    interactionType: "THREE_ANSWERS",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes: "Seeded as student-questions (three_answers). Matches workbook.",
  },

  // --- Comprehension ---
  {
    sourceItemKey: "j1-03",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "understand",
    originalPrompt: "ما الفكرة الرئيسة للخبر؟",
    normalizedPrompt: "Main idea of the news?",
    sourceOptions: [
      "احترام المعلم المصري القديم ودوره في نشر العلم",
      "طريقة صناعة أوراق البردي في المقابر",
      "أهمية تزيين جدران المقابر بالرسومات",
    ],
    sourceCorrectAnswer: "احترام المعلم المصري القديم ودوره في نشر العلم",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes: "Seeded as main-idea-choice (single_choice). Matches workbook.",
  },
  {
    sourceItemKey: "j1-04",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "sequence-events",
    originalPrompt: "صل كل حدث بمعناه",
    normalizedPrompt: "Match each event to its meaning",
    sourceOptions: [
      "تطوير قاعة الكتابة → الاهتمام بنشر الوعي",
      "العثور على البرديات → تخليد العلم وتقدير المعرفة",
      "جلوس الكاتب بوقار → الهيبة والاحترام",
    ],
    sourceCorrectAnswer: "evt1→val1, evt2→val2, evt3→val3",
    sourceModelAnswer: "",
    interactionType: "MATCHING",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes: "Seeded as event-meaning-matching (matching). Matches workbook.",
  },
  {
    sourceItemKey: "j1-05",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "review-achievement",
    originalPrompt: "حدد الشخصية الرئيسة في الخبر",
    normalizedPrompt: "Identify main character",
    sourceOptions: ["الكاتب / المعلم المصري القديم"],
    sourceCorrectAnswer: "الكاتب / المعلم المصري القديم",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Seeded as character-event-identification (matching), combining items 5+6 into one matching activity. Workbook expects SINGLE_CHOICE. Content correct but type differs.",
  },
  {
    sourceItemKey: "j1-06",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "review-achievement",
    originalPrompt: "حدد الحدث الأهم في النص",
    normalizedPrompt: "Identify most important event",
    sourceOptions: ["اكتشاف مقبرة كاتب قديم وبدء تطوير القاعة بالمتحف"],
    sourceCorrectAnswer: "اكتشاف مقبرة كاتب قديم وبدء تطوير القاعة بالمتحف",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "MERGED_WITH_REASON",
    mergedIntoSourceItemKey: "j1-05",
    notes:
      "Merged with j1-05 into character-event-identification matching activity in seed. Workbook expects separate SINGLE_CHOICE.",
  },
  {
    sourceItemKey: "j1-07",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "understand",
    originalPrompt: "أين عُثر على المقبرة؟",
    normalizedPrompt: "Where was the tomb found?",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Not directly seeded as SINGLE_CHOICE. Partially covered by comprehension-questions (fill_in_the_blank) which is an invented activity with different format. Needs new SINGLE_CHOICE activity with proper options.",
  },
  {
    sourceItemKey: "j1-08",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "understand",
    originalPrompt: "لماذا كانت المقبرة مهمة؟",
    normalizedPrompt: "Why was the tomb important?",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Not seeded. Needs new SINGLE_CHOICE activity with options from workbook content.",
  },
  {
    sourceItemKey: "j1-09",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "understand",
    originalPrompt: "ماذا يدل الاكتشاف على مكانة المعلم؟",
    normalizedPrompt: "What does discovery indicate about teacher status?",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes: "Not seeded. Needs new SINGLE_CHOICE activity.",
  },
  {
    sourceItemKey: "j1-10",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "think-and-create",
    originalPrompt: "اكتب نتيجتين ترتبتا على الاكتشاف",
    normalizedPrompt: "Write two results of discovery",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "1. معرفة أدوات الكتابة المستخدمة.\n2. إثبات مدى هيبة ومكانة المعلم.",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      'Seeded as discovery-results (three_answers type). Workbook specifies OPEN_TEXT for "two results". Type mismatch but content aligns.',
  },
  {
    sourceItemKey: "j1-11",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "listen",
    originalPrompt: "اختر العنوان الأنسب",
    normalizedPrompt: "Select best title",
    sourceOptions: [
      "أدوات الكتابة الخشبية",
      "المعلم المصري القديم ودوره في الحضارة",
      "المتاحف وتطوير القاعات القديمة",
    ],
    sourceCorrectAnswer: "المعلم المصري القديم ودوره في الحضارة",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: true,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as best-title-choice (single_choice) with audioAssetKey. Matches workbook.",
  },
  {
    sourceItemKey: "j1-12",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "understand",
    originalPrompt: "اختر الفكرة الرئيسة",
    normalizedPrompt: "Select main idea",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "MERGED_WITH_REASON",
    mergedIntoSourceItemKey: "j1-03",
    notes:
      'Same intent as j1-03 (main-idea-choice). The workbook lists both "Main idea of the news" and "Select main idea" — merged into single main-idea-choice activity.',
  },

  // --- Vocabulary ---
  {
    sourceItemKey: "j1-13",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "word-play",
    originalPrompt: "صل كل كلمة بمرادفها: عالم→باحث، مقبرة→مدفن، مهنة→حرفة",
    normalizedPrompt: "Synonyms matching: عالم→باحث, مقبرة→مدفن, مهنة→حرفة",
    sourceOptions: ["عالم→باحث", "مقبرة→مدفن", "مهنة→حرفة"],
    sourceCorrectAnswer: "عالم→باحث, مقبرة→مدفن, مهنة→حرفة",
    sourceModelAnswer: "",
    interactionType: "MATCHING",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Seeded as synonym-matching but with DIFFERENT word pairs (وقار→هيبة, يدوّن→يكتب, يسهم→يشارك). Workbook requires عالم→باحث, مقبرة→مدفن, مهنة→حرفة. Content mismatch needs correction.",
  },
  {
    sourceItemKey: "j1-14",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "word-play",
    originalPrompt:
      "صل كل كلمة بضدها: القديم→الحديث، العلم→الجهل، البداية→النهاية، احترام→ازدراء، تقدير→إهمال، عالِم→جاهل",
    normalizedPrompt:
      "Antonyms matching: القديم→الحديث, العلم→الجهل, البداية→النهاية, احترام→ازدراء, تقدير→إهمال, عالِم→جاهل",
    sourceOptions: [
      "القديم→الحديث",
      "العلم→الجهل",
      "البداية→النهاية",
      "احترام→ازدراء",
      "تقدير→إهمال",
      "عالِم→جاهل",
    ],
    sourceCorrectAnswer:
      "القديم→الحديث, العلم→الجهل, البداية→النهاية, احترام→ازدراء, تقدير→إهمال, عالِم→جاهل",
    sourceModelAnswer: "",
    interactionType: "MATCHING",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Seeded as two activities: antonym-matching (عظيمة/ينشر/وقار — wrong words) and antonyms-detailed (مكانة/احترام/تقدير/معلم — partially matching). Workbook has 6 pairs in one activity. Both seeded activities have content mismatches and need to be consolidated with correct pairs.",
  },

  // --- Ordering ---
  {
    sourceItemKey: "j1-15",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "sequence-events",
    originalPrompt:
      "رتب المجموعة أ: بدأ المتحف المصري مشروع تطوير القاعة → عرض المتحف دور المعلم → استخدم المعلم القديم البردية → أعجب الزوار بالعرض",
    normalizedPrompt:
      "Group A ordering: Museum project → Museum displayed teacher role → Teacher used papyrus → Visitors impressed",
    sourceOptions: [
      "بدأ المتحف المصري مشروع تطوير القاعة",
      "عرض المتحف دور المعلم",
      "استخدم المعلم القديم البردية",
      "أعجب الزوار بالعرض",
    ],
    sourceCorrectAnswer:
      "بدأ المتحف → عرض المتحف → استخدم المعلم → أعجب الزوار",
    sourceModelAnswer: "",
    interactionType: "ORDERING",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Seeded as event-ordering with 3 items (similar museum theme but different text and only 3 vs 4 items). Needs content update to match workbook 4-item sequence.",
  },
  {
    sourceItemKey: "j1-16",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "sequence-events",
    originalPrompt:
      "رتب المجموعة ب: وجود الكاتب في المجتمع → وفاته ودفنه → اكتشاف المقبرة → معرفة أهميته",
    normalizedPrompt:
      "Group B ordering: Scribe existence → Death and burial → Tomb discovery → Understanding importance",
    sourceOptions: [
      "وجود الكاتب في المجتمع",
      "وفاته ودفنه",
      "اكتشاف المقبرة",
      "معرفة أهميته",
    ],
    sourceCorrectAnswer:
      "وجود الكاتب → وفاته ودفنه → اكتشاف المقبرة → معرفة أهميته",
    sourceModelAnswer: "",
    interactionType: "ORDERING",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes: "Not seeded. Needs new ordering activity for Group B sequence.",
  },

  // --- Creative thinking ---
  {
    sourceItemKey: "j1-17",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "think-and-create",
    originalPrompt: "ماذا لو لم تُكتشف المقبرة؟",
    normalizedPrompt: "What if tomb had not been discovered?",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "لما عرفنا مكانة الكاتب العظيمة في المجتمع المصري القديم، ولضاع جزء كبير من تاريخ توثيق التعليم.",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as what-if-reflection (long_text). Shows model answers after submission. Matches workbook.",
  },

  // --- Self-assessment (ungraded) ---
  {
    sourceItemKey: "j1-18",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "prepare",
    originalPrompt: "ما شعورك قبل حصة اللغة العربية؟",
    normalizedPrompt: "Feelings before Arabic class",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Not seeded. The only J1 self-assessment (arabic-self-assessment) maps to item j1-19. This needs a new activity.",
  },
  {
    sourceItemKey: "j1-19",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "prepare",
    originalPrompt: "هل تقرأ العربية خارج المدرسة؟",
    normalizedPrompt: "Reading Arabic outside school",
    sourceOptions: [
      "أشعر بالسعادة والشغف",
      "أشعر بالهدوء والاعتياد",
      "أشعر بالملل أحياناً",
    ],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as arabic-self-assessment (self_assessment). Matches workbook.",
  },
  {
    sourceItemKey: "j1-20",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "review-achievement",
    originalPrompt: "هل تتخيل المشاهد أثناء الاستماع؟",
    normalizedPrompt: "Mental visualization while listening",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes: "Not seeded. Needs new self-assessment activity.",
  },
  {
    sourceItemKey: "j1-21",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "review-achievement",
    originalPrompt: "هل تستخدم كلمات عربية جديدة في حياتك اليومية؟",
    normalizedPrompt: "Using new Arabic words in daily life",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes: "Not seeded. Needs new self-assessment activity.",
  },
  {
    sourceItemKey: "j1-22",
    sourcePage: 0,
    journeySlug: "ancient-egyptian-teacher",
    stageSlug: "review-achievement",
    originalPrompt: "كيف تتصرف أثناء شرح المعلم؟",
    normalizedPrompt: "Behavior while teacher explains",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes: "Not seeded. Needs new self-assessment activity.",
  },

  // ============================================================================
  // JOURNEY 2: king-of-hearts (ملك القلوب)
  // Items 23–53
  // ============================================================================

  // --- Prediction ---
  {
    sourceItemKey: "j2-23",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "review-achievement",
    originalPrompt: "اكتب ثلاثة عناوين مناسبة",
    normalizedPrompt: "Write three suitable titles",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "1. زارع الأمل بأسوان\n2. طبيب القلوب الرحيم\n3. رحلة العطاء والعودة للوطن",
    interactionType: "THREE_ANSWERS",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes: "Seeded as yacoub-story-titles (three_answers). Matches workbook.",
  },
  {
    sourceItemKey: "j2-24",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "predict",
    originalPrompt: "توقع عنوان القصة",
    normalizedPrompt: "Predict the title",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "أتوقع أنها قصة طبيب عظيم يضحي بوقته وماله لعلاج قلوب المرضى والفقراء بالمجان.",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes: "Seeded as yacoub-title-prediction (short_text). Matches workbook.",
  },
  {
    sourceItemKey: "j2-25",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "think-and-create",
    originalPrompt: "اكتب ثلاثة أسئلة تود طرحها في مقابلة",
    normalizedPrompt: "Write three interview questions",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "1. ما الذي جعلك تختار جراحة القلب بالذات؟\n2. كيف تشعر بعد نجاح عملية معقدة لطفل صغير؟\n3. بم تنصح الأطفال الذين يتمنون أن يكونوا أطباء؟",
    interactionType: "THREE_ANSWERS",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-interview-questions (three_answers). Matches workbook.",
  },

  // --- Ordering ---
  {
    sourceItemKey: "j2-26",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "listen",
    originalPrompt: "رتب: سفر → اكتسابه الخبرة → عودته → إنشاء مركز القلب",
    normalizedPrompt:
      "Sequence: Travel → Gained experience → Return → Heart center establishment",
    sourceOptions: [
      "سفر مجدي يعقوب",
      "اكتسابه الخبرة",
      "عودته إلى مصر",
      "إنشاء مركز القلب",
    ],
    sourceCorrectAnswer: "سفر → اكتسابه الخبرة → عودته → إنشاء مركز القلب",
    sourceModelAnswer: "",
    interactionType: "ORDERING",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: true,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-stages-ordering (ordering) with 3 stages. Workbook has 4 items but core sequence matches. Minor content adjustment may be needed.",
  },
  {
    sourceItemKey: "j2-27",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "sequence-events",
    originalPrompt: "رتب مراحل الحياة: نشأة → حبه للطب → رحلته → جهوده → أثره",
    normalizedPrompt:
      "Life stages: Childhood → Love of medicine → Journey → Efforts → Legacy",
    sourceOptions: [
      "نشأة مجدي يعقوب",
      "حبه للطب",
      "رحلته العلمية",
      "جهوده الإنسانية",
      "أثره الباقي",
    ],
    sourceCorrectAnswer: "نشأة → حبه للطب → رحلته → جهوده → أثره",
    sourceModelAnswer: "",
    interactionType: "ORDERING",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-life-ordering (ordering) with 4 milestones. Workbook has 5 stages. Minor expansion needed.",
  },

  // --- Fill-blank ---
  {
    sourceItemKey: "j2-28",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "listen",
    originalPrompt: "عاد الدكتور مجدي يعقوب إلى مصر في عام ___",
    normalizedPrompt: "Dr. Magdi Yacoub returned to Egypt in year ___",
    sourceOptions: [],
    sourceCorrectAnswer: "2009",
    sourceModelAnswer: "",
    interactionType: "FILL_BLANK",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-return-year (fill_in_the_blank). Answer: 2009. Matches workbook.",
  },
  {
    sourceItemKey: "j2-29",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "understand",
    originalPrompt: "أُنشئ مركز القلب لخدمة ___",
    normalizedPrompt: "The heart center was established to serve ___",
    sourceOptions: [],
    sourceCorrectAnswer: "أهالي الصعيد",
    sourceModelAnswer: "",
    interactionType: "FILL_BLANK",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      'Seeded as yacoub-insist-reason (fill_in_the_blank) but with different prompt ("أصر الطبيب على إنشاء المركز بسبب [blank1]") and answer ("مساعدة الناس"). Workbook wants specific answer "أهالي الصعيد". Content mismatch.',
  },

  // --- Objective selection ---
  {
    sourceItemKey: "j2-30",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "understand",
    originalPrompt: "الجراح الهادئ يكون أقدر على تحقيق النجاح",
    normalizedPrompt: "Calm surgeon is: more capable of achieving success",
    sourceOptions: [
      "لأنه يجعله سريع الحركة",
      "لأنه يمنحه القدرة على تحقيق النجاح وتجنب الأخطاء",
      "لأنه يمنع المرضى من القلق",
    ],
    sourceCorrectAnswer: "لأنه يمنحه القدرة على تحقيق النجاح وتجنب الأخطاء",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-surgeon-calmness (single_choice). Matches workbook.",
  },
  {
    sourceItemKey: "j2-31",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "understand",
    originalPrompt: "الحل البديل: تدريب أطباء محليين",
    normalizedPrompt: "Alternative solution: training local doctors",
    sourceOptions: [
      "إرسال المرضى للعلاج خارج مصر",
      "تدريب أطباء محليين وتسيير قوافل طبية",
      "الاعتماد على المستشفيات الخاصة بالمدن الكبرى",
    ],
    sourceCorrectAnswer: "تدريب أطباء محليين وتسيير قوافل طبية",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-alternative-solution (single_choice). Matches workbook.",
  },
  {
    sourceItemKey: "j2-32",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "word-play",
    originalPrompt: "فائدة اللغة العربية: المساعدة على النجاح في المواد الأخرى",
    normalizedPrompt: "Benefit of Arabic: helping succeed in other subjects",
    sourceOptions: [
      "تساعد في الفهم الدقيق للمفاهيم الطبية والبحثية",
      "تقتصر على قراءة الكتب والقصص القديمة",
      "تحسن الخطوط والزخارف",
    ],
    sourceCorrectAnswer: "تساعد في الفهم الدقيق للمفاهيم الطبية والبحثية",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-arabic-practical-use (single_choice). Matches workbook.",
  },

  // --- Open thinking ---
  {
    sourceItemKey: "j2-33",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "think-and-create",
    originalPrompt: "اختر مشكلة واقترح حلين",
    normalizedPrompt: "Choose a problem and suggest two solutions",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "الحل 1: بناء مركز محلي. الحل 2: توفير وسائل مواصلات مجانية أو قوافل مجهزة.",
    interactionType: "PROBLEM_SOLUTION",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-problem-solutions (problem_solution). Matches workbook.",
  },
  {
    sourceItemKey: "j2-34",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "think-and-create",
    originalPrompt: "ما رأيك في شخصيته؟",
    normalizedPrompt: "Opinion about his character",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "هو قدوة عظيمة لأنه جسد معاني الرحمة والعطاء والتواضع.",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-character-opinion (long_text). Prompt combines opinion + role model question. Matches workbook.",
  },
  {
    sourceItemKey: "j2-35",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "think-and-create",
    originalPrompt: "هل تراه قدوة ولماذا؟",
    normalizedPrompt: "Is he a role model and why",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "MERGED_WITH_REASON",
    mergedIntoSourceItemKey: "j2-34",
    notes:
      "Merged into j2-34 (yacoub-character-opinion). The seed prompt covers both opinion and role model aspects in one activity.",
  },
  {
    sourceItemKey: "j2-36",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "think-and-create",
    originalPrompt: "اقترح بدائل إذا لم تتوفر الموارد",
    normalizedPrompt: "Suggest alternatives if resources unavailable",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "عيادة فحص متنقلة أو شبكة تطوعية تنسق مع مستشفيات جامعية.",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-funding-alternatives (long_text). Matches workbook.",
  },
  {
    sourceItemKey: "j2-37",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "think-and-create",
    originalPrompt: "أعد سرد القصة",
    normalizedPrompt: "Retell the story",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "طبيب مصري نشأ محباً لخدمة الناس، تفوق وسافر لبريطانيا ونال الشهرة العالمية، ثم عاد ليبني مركز قلب مجاني للأطفال.",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes: "Seeded as yacoub-story-retell (retell_story). Matches workbook.",
  },
  {
    sourceItemKey: "j2-38",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "understand",
    originalPrompt: "لماذا أصر على إنشاء المركز؟",
    normalizedPrompt: "Why he insisted on creating the center",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Seeded as yacoub-insist-reason (fill_in_the_blank). Workbook expects OPEN_TEXT. Type mismatch — seed uses fill-blank format instead of open reflection.",
  },
  {
    sourceItemKey: "j2-39",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "understand",
    originalPrompt: "لماذا واجه المشروع صعوبات؟",
    normalizedPrompt: "Why project faced difficulties",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Seeded as yacoub-biggest-challenge (fill_in_the_blank). Workbook expects OPEN_TEXT. Type mismatch.",
  },
  {
    sourceItemKey: "j2-40",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "think-and-create",
    originalPrompt: "اقترح نهاية أخرى للقصة",
    normalizedPrompt: "Suggest another ending",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Not seeded. Needs new open_text activity for suggesting alternative ending.",
  },
  {
    sourceItemKey: "j2-41",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "think-and-create",
    originalPrompt: "صمم مشروعاً إنسانياً: المشكلة، الحل، النهاية",
    normalizedPrompt: "Build humanitarian project: problem, solution, ending",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "المشكلة: صعوبة القراءة لفاقدي البصر.\nالحل: تطبيق مجاني يحول الكتب لقصص مسموعة.\nالنتيجة: تمكين المكفوفين من التعلم.",
    interactionType: "STORY_BUILDER",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-humanitarian-project (story_builder). Matches workbook.",
  },
  {
    sourceItemKey: "j2-42",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "think-and-create",
    originalPrompt: "صمم نهاية مختلفة للقصة",
    normalizedPrompt: "Design different ending",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Not seeded. Similar to j2-40 but distinct workbook item. Needs new activity.",
  },
  {
    sourceItemKey: "j2-43",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "think-and-create",
    originalPrompt: "اقترح مشكلة مشابهة وحلها",
    normalizedPrompt: "Suggest similar problem and solution",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "الحل 1: جدول يومي مرن.\nالحل 2: تقسيم المهام الكبيرة لمهام صغيرة.",
    interactionType: "PROBLEM_SOLUTION",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-student-problem (problem_solution). Matches workbook.",
  },
  {
    sourceItemKey: "j2-44",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "word-play",
    originalPrompt: "اكتب كلمة جديدة في جملة",
    normalizedPrompt: "Write new word in sentence",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "الكلمة: التعاطف. الجملة: التعاطف مع المرضى يهدئ من خوفهم.",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes: "Seeded as yacoub-new-word (short_text). Matches workbook.",
  },

  // --- Agree-disagree ---
  {
    sourceItemKey: "j2-45",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "review-achievement",
    originalPrompt: "العمل الإنساني أهم من الشهرة",
    normalizedPrompt: "Humanitarian work is more important than fame",
    sourceOptions: ["موافق", "غير موافق"],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "AGREE_DISAGREE",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-agree-disagree (agree_disagree). Both j2-45 and j2-46 are combined in one activity with two statements. Matches workbook.",
  },
  {
    sourceItemKey: "j2-46",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "review-achievement",
    originalPrompt: "الإصرار سبب النجاح",
    normalizedPrompt: "Persistence is the cause of success",
    sourceOptions: ["موافق", "غير موافق"],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "AGREE_DISAGREE",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "MERGED_WITH_REASON",
    mergedIntoSourceItemKey: "j2-45",
    notes:
      "Merged with j2-45 into yacoub-agree-disagree. Both statements presented in one activity.",
  },

  // --- Self-assessment (J2) ---
  {
    sourceItemKey: "j2-47",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "prepare",
    originalPrompt: "بماذا تشعر عند تلقي المديح؟",
    normalizedPrompt: "Feeling when receiving praise",
    sourceOptions: [
      "الفخر والرغبة في بذل المزيد",
      "السعادة والارتياح العام",
      "الخجل والتردد",
    ],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-praise-assessment (self_assessment). Matches workbook.",
  },
  {
    sourceItemKey: "j2-48",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "prepare",
    originalPrompt: "لماذا تحرص على درجة عالية في العربية؟",
    normalizedPrompt: "Motivation for Arabic grade",
    sourceOptions: [
      "لحبي الشديد للغة العربية",
      "لإسعاد والدي وتقدير معلمي",
      "لأكون متفوقاً ومتميزاً",
    ],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-score-motivation (self_assessment). Matches workbook.",
  },
  {
    sourceItemKey: "j2-49",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "sequence-events",
    originalPrompt: "سلوك الاستماع الصحيح",
    normalizedPrompt: "Listening behavior",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Seeded as yacoub-listening-behavior (checklist type, graded). Workbook expects SELF_ASSESSMENT (ungraded). Type and grading mode mismatch.",
  },
  {
    sourceItemKey: "j2-50",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "prepare",
    originalPrompt: "المهارات التي تحسنت فيها",
    normalizedPrompt: "Skills improved",
    sourceOptions: [
      "الاستماع بتركيز",
      "قراءة النصوص بطلاقة",
      "كتابة الجمل والتعبير عن الرأي",
    ],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-improvement-checklist (self_assessment). Matches workbook.",
  },
  {
    sourceItemKey: "j2-51",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "review-achievement",
    originalPrompt: "لماذا تحب المسابقات؟",
    normalizedPrompt: "Why competitions",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes: "Not seeded. Needs new self-assessment activity.",
  },
  {
    sourceItemKey: "j2-52",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "prepare",
    originalPrompt: "تشجيع الوالدين",
    normalizedPrompt: "Parent encouragement",
    sourceOptions: [
      "تشجيع دائم وقوي",
      "تشجيع كافٍ ومساعد عند الحاجة",
      "أعتمد على تحفيزي الذاتي",
    ],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as yacoub-encouragement-assessment (self_assessment). Covers parent + teacher encouragement together.",
  },
  {
    sourceItemKey: "j2-53",
    sourcePage: 0,
    journeySlug: "king-of-hearts",
    stageSlug: "prepare",
    originalPrompt: "تشجيع المعلم",
    normalizedPrompt: "Teacher encouragement",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "MERGED_WITH_REASON",
    mergedIntoSourceItemKey: "j2-52",
    notes:
      "Merged with j2-52 into yacoub-encouragement-assessment. Seed activity covers both parent and teacher encouragement.",
  },

  // ============================================================================
  // JOURNEY 3: my-body-is-a-trust (جسدي أمانة)
  // Items 54–77
  // ============================================================================

  // --- Objective (storagePolicy=OBJECTIVE_RESULT_ONLY) ---
  {
    sourceItemKey: "j3-54",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "listen",
    originalPrompt: "ما الأجزاء الخاصة في أجسادنا؟",
    normalizedPrompt: "Which body areas are private?",
    sourceOptions: [
      "أجزاء مكشوفة يمكن للجميع رؤيتها",
      "أجزاء خاصة جداً ومغطاة لا يحق لأحد أن يراها أو يلمسها",
      "الملابس الرياضية التي نرتديها فقط",
    ],
    sourceCorrectAnswer:
      "أجزاء خاصة جداً ومغطاة لا يحق لأحد أن يراها أو يلمسها",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "OBJECTIVE_RESULT_ONLY",
    requiresAudio: true,
    implementationStatus: "IMPLEMENTED",
    notes: "Seeded as safety-private-parts (single_choice). Matches workbook.",
  },
  {
    sourceItemKey: "j3-55",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "listen",
    originalPrompt: "ما معنى الخصوصية؟",
    normalizedPrompt: "Meaning of privacy",
    sourceOptions: [
      "نشارك كل شيء مع الآخرين",
      "لكل شخص خصوصية تامة وحدود تخص جسده",
      "نلعب مع الجميع دون حذر",
    ],
    sourceCorrectAnswer: "لكل شخص خصوصية تامة وحدود تخص جسده",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "OBJECTIVE_RESULT_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as safety-privacy-meaning (single_choice). Matches workbook.",
  },
  {
    sourceItemKey: "j3-56",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "understand",
    originalPrompt: "ماذا تفعل عند التعرض للأذى؟",
    normalizedPrompt: "What to do when harmed",
    sourceOptions: [
      "أسكت ولا أخبر أحداً",
      "أقول كُفّ وأبتعد وأخبر والديّ",
      "أنتظر حتى يتكرر الأمر",
    ],
    sourceCorrectAnswer: "أقول كُفّ وأبتعد وأخبر والديّ",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "OBJECTIVE_RESULT_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes: "Seeded as safety-abuse-action (single_choice). Matches workbook.",
  },
  {
    sourceItemKey: "j3-57",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "understand",
    originalPrompt: "ماذا تفعل عند الشعور بعدم الارتياح؟",
    normalizedPrompt: "What to do when uncomfortable",
    sourceOptions: [
      "خطأ يجب إخفاؤه عن الأهل",
      "حق طبيعي وواجب لحمايتك",
      "سر لا يجب مناقشته مع المدرسين",
    ],
    sourceCorrectAnswer: "حق طبيعي وواجب لحمايتك",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "OBJECTIVE_RESULT_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as safety-uncomfortable-touch (single_choice). Matches workbook.",
  },
  {
    sourceItemKey: "j3-58",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "predict",
    originalPrompt: "توقع من عنوان القصة",
    normalizedPrompt: "Predicting from story title",
    sourceOptions: [
      "جسدي ملك لي وحدي ويجب أن أحافظ عليه",
      "هناك حدوداً خاصة لا يحق لأحد تجاوزها",
    ],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "OBJECTIVE_RESULT_ONLY",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Seeded as safety-title-reaction (self_assessment type, ungraded). Workbook expects SINGLE_CHOICE with OBJECTIVE grading. Type and grading mode mismatch.",
  },
  {
    sourceItemKey: "j3-59",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "sequence-events",
    originalPrompt: "ماذا يمكن للطالب أن يفعل بالنص المسموع؟",
    normalizedPrompt: "What student can do with listened text",
    sourceOptions: [
      "رسم لوحة إرشادية تعبر عن الأمان",
      "كتابة ملخص إرشادي وإلقائه بالإذاعة",
      "تجاهل مناقشة الفكرة",
    ],
    sourceCorrectAnswer: "كتابة ملخص إرشادي وإلقائه بالإذاعة",
    sourceModelAnswer: "",
    interactionType: "SINGLE_CHOICE",
    gradingMode: "OBJECTIVE",
    storagePolicy: "OBJECTIVE_RESULT_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as safety-representation-choice (single_choice). Matches workbook.",
  },

  // --- Word bank ---
  {
    sourceItemKey: "j3-60",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "understand",
    originalPrompt: "أكمل بالكلمات: خطأ، خصوصية، أمان، إيذاء، كف",
    normalizedPrompt: "Words: خطأ, خصوصية, أمان, إيذاء, كف",
    sourceOptions: ["خطأ", "خصوصية", "أمان", "إيذاء", "كف"],
    sourceCorrectAnswer: "خصوصية, كف, خطأ",
    sourceModelAnswer: "",
    interactionType: "WORD_BANK",
    gradingMode: "OBJECTIVE",
    storagePolicy: "FULL_RESPONSE",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Seeded as safety-word-bank-fill (fill_in_the_blank type). Workbook specifies WORD_BANK interaction type. Type mismatch — current implementation uses fill_in_the_blank format instead of word bank selection.",
  },

  // --- Open (storagePolicy=COMPLETION_ONLY) ---
  {
    sourceItemKey: "j3-61",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "think-and-create",
    originalPrompt: "اقترح نهاية جديدة",
    normalizedPrompt: "Suggest new ending",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "باح الطفل لوالديه بشجاعة، فحضناه وطمأناه، وأبلغ والده إدارة المدرسة.",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as safety-alternative-ending (creative_ending). Matches workbook. storagePolicy=COMPLETION_ONLY per J3 safety policy.",
  },
  {
    sourceItemKey: "j3-62",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "think-and-create",
    originalPrompt: "لخص النص",
    normalizedPrompt: "Summarize text",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "أجسادنا مميزة ولها خصوصية تامة. واجبنا قول كُفّ والبوح فوراً للأهل.",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes: "Seeded as safety-story-summary (retell_story). Matches workbook.",
  },
  {
    sourceItemKey: "j3-63",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "think-and-create",
    originalPrompt: "أعد سرد القصة",
    normalizedPrompt: "Retell story",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "جسدي مميز وخاص بي. عندما يحضنني والداي أشعر بالأمان.",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes: "Seeded as safety-story-retell (retell_story). Matches workbook.",
  },
  {
    sourceItemKey: "j3-64",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "review-achievement",
    originalPrompt: "اكتب ثلاثة عناوين مناسبة",
    normalizedPrompt: "Three suitable titles",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "1. حدود جسدي الآمنة\n2. شجاعة البوح للأهل\n3. أنا ذكي وجسدي أمانة",
    interactionType: "THREE_ANSWERS",
    gradingMode: "OPEN",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes: "Seeded as safety-safe-titles (three_answers). Matches workbook.",
  },
  {
    sourceItemKey: "j3-65",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "predict",
    originalPrompt: "توقع عنواناً للقصة",
    normalizedPrompt: "Predict a title",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Not separately seeded as OPEN_TEXT. safety-title-reaction covers prediction but as self_assessment with fixed options, not open text. Needs new activity.",
  },
  {
    sourceItemKey: "j3-66",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "think-and-create",
    originalPrompt: "اكتب نهايتين مختلفتين",
    normalizedPrompt: "Two different endings",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "النهاية 1: تصرف المعلم بحزم.\nالنهاية 2: تدريب الزملاء على شجاعة البوح.",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as safety-double-endings (creative_ending). Matches workbook.",
  },
  {
    sourceItemKey: "j3-67",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "word-play",
    originalPrompt: "اكتب كلمة جديدة في جملة",
    normalizedPrompt: "New word in sentence",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer:
      "جسدي له خصوصية تامة ولا أسمح لأي غريب بتجاوز هذه الحدود.",
    interactionType: "OPEN_TEXT",
    gradingMode: "OPEN",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes: "Seeded as safety-word-sentence (short_text). Matches workbook.",
  },

  // --- Self-assessment (J3, ungraded, 10 items: 68-77) ---
  {
    sourceItemKey: "j3-68",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "prepare",
    originalPrompt: "ما شعورك تجاه العربية؟",
    normalizedPrompt: "Feelings toward Arabic",
    sourceOptions: [
      "أشعر بالأمان والطمأنينة لمعرفتي بها",
      "أشعر بالرغبة في فهم المزيد",
    ],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as safety-arabic-feelings (self_assessment). Matches workbook.",
  },
  {
    sourceItemKey: "j3-69",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "prepare",
    originalPrompt: "أهمية فهم حدود الجسد",
    normalizedPrompt: "Importance of understanding body boundaries",
    sourceOptions: ["لأحمي جسدي وأخبر والدي", "لأكون واعياً وذكياً في تصرفاتي"],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as safety-arabic-importance (self_assessment). Matches workbook.",
  },
  {
    sourceItemKey: "j3-70",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "prepare",
    originalPrompt: "كيف تحافظ على تفوقك وأمانك؟",
    normalizedPrompt: "Maintaining excellence and safety",
    sourceOptions: ["أتحدث مع والدي بصدق تام", "أنتبه دائماً لتعليمات السلامة"],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as safety-arabic-excellence (self_assessment). Matches workbook.",
  },
  {
    sourceItemKey: "j3-71",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "review-achievement",
    originalPrompt: "سلوك سماع كلمة جديدة",
    normalizedPrompt: "New word behavior",
    sourceOptions: ["أسأل والدي أو معلمي فوراً", "أحاول تخمينه بنفسي"],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as safety-new-word-behavior (self_assessment). Matches workbook.",
  },
  {
    sourceItemKey: "j3-72",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "review-achievement",
    originalPrompt: "ماذا تفعل أثناء شرح المعلم؟",
    normalizedPrompt: "Teacher explanation behavior",
    sourceOptions: ["أنصت بكل جوارحي", "أشارك بالإجابة عن الأسئلة بوعي"],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as safety-classroom-attention (self_assessment). Matches workbook.",
  },
  {
    sourceItemKey: "j3-73",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "prepare",
    originalPrompt: "شعورك بعد سماع القصة",
    normalizedPrompt: "After story feelings",
    sourceOptions: [
      "أشعر بالثقة في تطبيق قواعد الأمان",
      "سأطلب مساعدة بابا وماما دائماً",
    ],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "IMPLEMENTED",
    notes:
      "Seeded as safety-final-self-checks (self_assessment). Broadly maps to post-story feelings assessment.",
  },
  {
    sourceItemKey: "j3-74",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "review-achievement",
    originalPrompt: "سلوك الاستماع",
    normalizedPrompt: "Listening behavior",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes:
      "Not seeded as self_assessment. safety-listening-rules (checklist, graded) is in word-play stage but is a different activity type. Needs new self-assessment activity.",
  },
  {
    sourceItemKey: "j3-75",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "review-achievement",
    originalPrompt: "لماذا تحب العربية؟",
    normalizedPrompt: "Why likes Arabic",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes: "Not seeded. Needs new self-assessment activity.",
  },
  {
    sourceItemKey: "j3-76",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "review-achievement",
    originalPrompt: "استخدام كلمات جديدة",
    normalizedPrompt: "New words usage",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes: "Not seeded. Needs new self-assessment activity.",
  },
  {
    sourceItemKey: "j3-77",
    sourcePage: 0,
    journeySlug: "my-body-is-a-trust",
    stageSlug: "review-achievement",
    originalPrompt: "الواجبات المنزلية",
    normalizedPrompt: "Homework habits",
    sourceOptions: [],
    sourceCorrectAnswer: "",
    sourceModelAnswer: "",
    interactionType: "SELF_ASSESSMENT",
    gradingMode: "SELF_ASSESSMENT",
    storagePolicy: "COMPLETION_ONLY",
    requiresAudio: false,
    implementationStatus: "REVIEW_ACTIVITY",
    notes: "Not seeded. Needs new self-assessment activity.",
  },
];

// ============================================================================
// Summary Counts
// ============================================================================

export function getInventorySummary() {
  const total = workbookActivityInventory.length;
  const implemented = workbookActivityInventory.filter(
    (i) => i.implementationStatus === "IMPLEMENTED",
  ).length;
  const review = workbookActivityInventory.filter(
    (i) => i.implementationStatus === "REVIEW_ACTIVITY",
  ).length;
  const merged = workbookActivityInventory.filter(
    (i) => i.implementationStatus === "MERGED_WITH_REASON",
  ).length;
  const blocked = workbookActivityInventory.filter(
    (i) => i.implementationStatus === "BLOCKED_CONTENT_REVIEW",
  ).length;

  return { total, implemented, review, merged, blocked };
}

// ============================================================================
// Invented Activities — seeded in DB but NOT in workbook
// ============================================================================
// These activities exist in prisma/seed.ts and DB but do not correspond
// to any workbook item. They were created during previous implementation.
//
// 1. main-idea-open (J1, understand, short_text)
//    "الفكرة الرئيسة بأسلوبك" — open text version of main idea.
//    No workbook item asks for open-text main idea.
//
// 2. comprehension-questions (J1, understand, fill_in_the_blank)
//    "أسئلة حول مقبرة الكاتب" — 3 specific blanks about papyrus/cushion/scribe.
//    No workbook item matches these specific fill-blank questions.
//
// 3. safety-listening-rules (J3, word-play, checklist)
//    "سلوك الأمان والاستماع" — graded checklist about listening rules.
//    No distinct workbook item; J3 listening self-assessment is separate (j3-74).
//
// 4. safety-ending-rethought (J3, think-and-create, creative_ending)
//    "نهاية أخرى ملائمة للطفل" — redundant with j3-61 (suggest new ending)
//    and j3-66 (two different endings). No separate workbook item.
// ============================================================================
